### ISSUE TITLE
class-03: Home and About nav links should act as tabs

### ISSUE THREAD

**Issue by caraldi** [caraldi/portfolio-assignment#11]
Debug articleView.handleMainNav event handler to achieve "single page app": 
- [x] Data attributes are consistent/correct
- [x]  index.html contains appropriate sections with ids 
- [x] When nav link is clicked, associated content displays with all other sections hidden

**Comment by nsmeds** [comment]
writingSamplesView.js

- [ ] Line 36:  As of now the console throws an error that preventDefault() is being called on undefined. Move (event) argument from this function call to the function call on line 37 and it should work.

- [ ] Line 41: var is defined as selectedContent but referenced on line 43 as $selectedContent. Add the $ to the var declaration and you should avoid an error there.

index.html
- [ ] Line 46-47: Add a data-content="" attribute to each of your tabs, referencing the id of the linked section in the quotes. For example: 
`<li data-content="about" class="tab"><a href="#" class="icon-number">About</a></li>)`
